version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laranierp-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - anierp-laravel

    web:
        image: nginx:alpine
        container_name: brini-nginx
        restart: unless-stopped
        ports:
            - "8003:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - anierp-laravel

    db:
        image: mysql:5.7
        platform: linux/amd64
        container_name: brini-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: anierp
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - anierp-laravel

    phpmyadmin:
        image: phpmyadmin:latest
        platform: linux/amd64
        container_name: brini-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "8005:80"
        networks:
            - anierp-laravel

networks:
    anierp-laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
